### ISSUE TITLE
Treat the bot as a button

### ISSUE THREAD

**Issue by Bboy486** [tomwpublic/hubitat_switchbot#9]
I installed your driver and was able to pair the bot (i just have the bot switch) without issues. However, when I bring it into webcore, none of the push, turn on, toggle work. Is there a way to get the function to actually toggle so that is presses the paddle switch which it is on?

**Comment by tomwpublic** [comment]
I am not 100% sure, but I have hunch that push() wasn't working because I neglected to declare the PushableButton capability.  I made this change in version 0.9.9 of the SwitchBot Bot driver (in the main repo).  Will you please give this a try?

With this change, I think that a switch and button press should both work, assuming your Bot is put into a mode that would support those in the SwitchBot app.

I don't know what toggle might map to from webcore into Hubitat. Is there another community-supplied Hubitat driver that works with toggle that you know of so I could check it as an example?

**Comment by Bboy486** [comment]
Yes, I will try.

**Comment by tomwpublic** [comment]
Thank you. I updated the version on my HPM listing. So you can upgrade to the new version using HPM.

**Comment by Bboy486** [comment]
I tried and it just spins and doesn't see a new update. 

No Updates Available
All packages are up to date, click Next to return to the Main Menu.

Edit: i copied the driver code and replaced. The push command still doesnt work.

**Comment by tomwpublic** [comment]
My mistake, I missed an edit. Please try again.

**Comment by Bboy486** [comment]
Update https://github.com/tomwpublic/hubitat_switchbot/blob/main/switchbotBot again? I did not see a commit on that (2 hours ago)

**Comment by tomwpublic** [comment]
You can update just that file, or you can upgrade to 0.9.9 with HPM.

**Comment by Bboy486** [comment]
I did that but it still isn't working.

**Comment by tomwpublic** [comment]
What isn't working? Do you not have version 0.9.9 of the Bot driver? Does the action not work from webcore, and is there a debug print or anything that gives a clue? What mode do you have the Bot set to in the SwitchBot app?

**Comment by Bboy486** [comment]
I updated to the newest commit. The push or toggle or turn on does not activate the bot. 
Change history:
0.9.9 - @tomw - Add PushableButton.
In webcore the piston fires but the device does not activate. 
Switch mode in the app.

<html>
<body>


8/2/2021, 9:45:28 PM +460ms
--
+5ms | ╔Received event [----].time = xxxxx with a delay of 49ms, canQueue: true, calledMyself: false
+13ms | ║Runtime (5270 bytes) successfully initialized in 1ms (v0.3.113.20210703_HE)
+15ms | ║╔Execution stage started
+895ms | ║║Executed [Bot 64-Bot].push (875ms)
+901ms | ║╚Execution stage complete. (885ms)
+927ms | ║Setting up scheduled job for Mon, Aug 2 2021 @ 9:45:38 PM MST (in 9079ms)
+928ms | ╚Event processed successfully (926ms)
8/2/2021, 9:45:18 PM +458ms

**Comment by tomwpublic** [comment]
Ok, thanks for clarifying. Trying to narrow down where it might be failing- do any of the commands work if you run them from the Hubitat virtual device page? If so, I'll have to add some more logging to figure out what is coming in from webcore.

**Comment by tomw** [comment]
Hi folks. Sorry to interrupt! I've been getting tagged in this repo a fair few times over the past week or two, but I think you mean @tomwpublic rather than @tomw :)

**Comment by tomwpublic** [comment]
Sorry for the spam @tomw .

**Comment by Bboy486** [comment]
> Ok, thanks for clarifying. Trying to narrow down where it might be failing- do any of the commands work if you run them from the Hubitat virtual device page? If so, I'll have to add some more logging to figure out what is coming in from webcore.

No they do not

**Comment by tomwpublic** [comment]
Ok, something lower than webcore is the issue if it doesn't even work at the Hubitat level.

One thing to check: have you enabled the Cloud Service in the config page for your bot in the SwitchBot app?

**Comment by Bboy486** [comment]
Yes cloud service is enabled.


 ![Screenshot_20210809-174827_SwitchBot.jpg](https://user-images.githubusercontent.com/16495657/128791862-db0db6df-0aba-47c8-8c11-c9c793543f09.jpg)

**Comment by tomwpublic** [comment]
Are you on the Hubitat forums?  I'd like to contact you there so we can iterate more quickly on troubleshooting.  My name over there is 'tomw'.

**Comment by Bboy486** [comment]
I am but not that often. I think I might have fixed it. I removed
everything and did power cycles to both hubs. I did a test and was able to
get the piston to toggle. I don't think push works though. But toggle (not
on or off) did it once. I'll let it run for a day and report if the
issue persists. Feel free to close this in the meantime.

**Comment by tomwpublic** [comment]
I can't remember since it has been a while, but I recall some of the commands only work based on the mode you have set in the SwitchBot app.  So, for example, if you selected switch mode then only On/Off work.

Don't quote me on that, though, because it seemed to vary some depending on the specific mixture of settings I was using.  I found that it made sense to just support all possible SwitchBot API commands in this integration and then test to figure out which ones worked for the functionality that I wanted.  Then use that testing results to determine which to use in my external automations.

I'm glad that it seems to be working now.  Hopefully it stays that way, but post back here or on the Hubitat forums if not.
